---
- hosts: all
  become: false
  gather_facts: false

#- include: deployment_user.yml
#  when: "'vagrant' in {{ ansible_ssh_user }}"

- include: shorewall.yml
#  when: ansible_ssh_user == 'vagrant'
#  when: "'shorewall' in {{ group_names }}"
